import type { Transaction, HouseholdTask, ExpenseCategory, FamilyMember, Wallet, CategoryBudget, FamilyInvitation } from './types';

export const INITIAL_MEMBERS: FamilyMember[] = [
  {
    id: 'm1',
    name: 'Bố Minh',
    email: 'owner@test.com',
    role: 'OWNER',
    roleLabel: 'Chủ Hộ Gia Đình',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'm2',
    name: 'Mẹ Lan',
    email: 'member@test.com',
    role: 'MEMBER',
    roleLabel: 'Thành Viên Gia Đình',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'm3',
    name: 'Bé Bi',
    email: 'viewer@test.com',
    role: 'VIEWER',
    roleLabel: 'Trẻ Em',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250',
  },
];

export const INITIAL_WALLETS: Wallet[] = [
  {
    id: 'w-fund',
    name: 'Quỹ gia đình chung',
    type: 'Quỹ chung',
    balance: 48250000,
    initialBalance: 48250000,
    ownerName: 'Gia đình',
    active: true,
  },
  {
    id: 'w-mb',
    name: 'MB Bank',
    type: 'Ngân hàng',
    balance: 15000000,
    initialBalance: 15000000,
    ownerName: 'Bố Minh',
    active: true,
  },
  {
    id: 'w-cash',
    name: 'Tiền mặt',
    type: 'Tiền mặt',
    balance: 3000000,
    initialBalance: 3000000,
    ownerName: 'Bố Minh',
    active: true,
  },
  {
    id: 'w-momo',
    name: 'MoMo',
    type: 'Ví điện tử',
    balance: 2000000,
    initialBalance: 2000000,
    ownerName: 'Bố Minh',
    active: true,
  },
  {
    id: 'w-lan-vcb',
    name: 'Vietcombank Mẹ Lan',
    type: 'Ngân hàng',
    balance: 12800000,
    initialBalance: 12800000,
    ownerName: 'Mẹ Lan',
    active: true,
  },
  {
    id: 'w-savings',
    name: 'Tiết kiệm tích lũy',
    type: 'Tiết kiệm',
    balance: 3250000,
    initialBalance: 3250000,
    ownerName: 'Gia đình',
    active: true,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'c1',
    title: 'Đóng góp Quỹ chung - Đầu tháng',
    user: 'Bố Minh',
    userId: 'm1',
    time: '08:00',
    date: '01/10/2026',
    amount: 25000000,
    type: 'contribution',
    category: 'Đóng góp quỹ',
    iconType: 'salary',
    destinationWalletId: 'w-fund',
    destinationWalletName: 'Quỹ gia đình chung',
    note: 'Nộp tiền lương tháng 10 vào quỹ gia đình',
  },
  {
    id: 'c2',
    title: 'Đóng góp Quỹ chung - Đầu tháng',
    user: 'Mẹ Lan',
    userId: 'm2',
    time: '08:30',
    date: '01/10/2026',
    amount: 20000000,
    type: 'contribution',
    category: 'Đóng góp quỹ',
    iconType: 'salary',
    destinationWalletId: 'w-fund',
    destinationWalletName: 'Quỹ gia đình chung',
    note: 'Đóng góp thu chi kinh doanh',
  },
  {
    id: 'c3',
    title: 'Quỹ tiết kiệm tích lũy chuyển vào',
    user: 'Quỹ tiết kiệm',
    userId: 'm-savings',
    time: '09:00',
    date: '01/10/2026',
    amount: 3250000,
    type: 'contribution',
    category: 'Đóng góp quỹ',
    iconType: 'deposit',
    destinationWalletId: 'w-fund',
    destinationWalletName: 'Quỹ gia đình chung',
    note: 'Lãi tiết kiệm & tích lũy',
  },
  {
    id: 't1',
    title: 'Bách hóa Xanh',
    user: 'Mẹ Lan',
    userId: 'm2',
    time: '08:15',
    date: '04/10/2026',
    amount: -450000,
    type: 'expense',
    category: 'Ăn uống gia đình',
    iconType: 'shopping',
    sourceWalletId: 'w-lan-vcb',
    sourceWalletName: 'Vietcombank Mẹ Lan',
  },
  {
    id: 't2',
    title: 'Tiền lương tháng 10',
    user: 'Bố Minh',
    userId: 'm1',
    time: '09:00',
    date: '03/10/2026',
    amount: 35000000,
    type: 'income',
    category: 'Thu nhập',
    iconType: 'salary',
    destinationWalletId: 'w-mb',
    destinationWalletName: 'MB Bank',
  },
  {
    id: 't3',
    title: 'Tiền sữa bột cho con',
    user: 'Mẹ Lan',
    userId: 'm2',
    time: '17:30',
    date: '02/10/2026',
    amount: -820000,
    type: 'expense',
    category: 'Bé yêu',
    iconType: 'baby',
    sourceWalletId: 'w-fund',
    sourceWalletName: 'Quỹ gia đình chung',
  },
];

export const INITIAL_BUDGET_LIMITS: CategoryBudget[] = [
  { id: 'b1', category: 'Ăn uống gia đình', limit: 5000000 },
  { id: 'b2', category: 'Giáo dục con cái', limit: 5000000 },
  { id: 'b3', category: 'Mua sắm sinh hoạt', limit: 3000000 },
  { id: 'b4', category: 'Giải trí & du lịch', limit: 1500000 },
  { id: 'b5', category: 'Di chuyển', limit: 2000000 },
  { id: 'b6', category: 'Bé yêu', limit: 3000000 },
];

export const INITIAL_INVITATIONS: FamilyInvitation[] = [
  {
    id: 'inv-1',
    email: 'chuba@test.com',
    role: 'MEMBER',
    status: 'pending',
    createdAt: '03/10/2026',
    invitedBy: 'Bố Minh',
  },
];

export const INITIAL_TASKS: HouseholdTask[] = [
  {
    id: 'task-1',
    title: 'Đi chợ siêu thị cuối tuần',
    time: 'Hôm nay, 17:30',
    assignedTo: 'Bố Minh',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    tag: 'Ưu tiên',
    priority: true,
    completed: false,
  },
  {
    id: 'task-2',
    title: 'Đóng tiền học tiếng Anh cho bé...',
    amount: 2450000,
    assignedTo: 'Mẹ Lan',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
    tag: 'Học phí',
    priority: false,
    completed: false,
  },
];

export const MONTHLY_EXPENSES: ExpenseCategory[] = [
  { name: 'Ăn uống gia đình', percentage: 38, amount: 6365000, color: '#056839' },
  { name: 'Giáo dục con cái', percentage: 25, amount: 4187500, color: '#78350F' },
  { name: 'Mua sắm sinh hoạt', percentage: 18, amount: 3015000, color: '#0891B2' },
  { name: 'Giải trí & du lịch', percentage: 12, amount: 2010000, color: '#EA580C' },
  { name: 'Khoản khác', percentage: 7, amount: 1172500, color: '#94A3B8' },
];

export const WEEKLY_EXPENSES: ExpenseCategory[] = [
  { name: 'Ăn uống gia đình', percentage: 45, amount: 1800000, color: '#056839' },
  { name: 'Mua sắm sinh hoạt', percentage: 22, amount: 880000, color: '#0891B2' },
  { name: 'Giải trí & du lịch', percentage: 18, amount: 720000, color: '#EA580C' },
  { name: 'Khoản khác', percentage: 15, amount: 600000, color: '#94A3B8' },
];

